import imgDummy from "../assets/images/img-dummy.png";

const dummy = [
    {
        id: 1,
        title: "Deluxe",
        type: "Deluxe",
        cost: 320000,
        image: imgDummy,
        rating: 4.8,
        capacity: 10,
        activeSession: 1,
    },
    {
        id: 2,
        title: "Suite",
        type: "Suite",
        cost: 320000,
        image: imgDummy,
        rating: 4.8,
        capacity: 7,
        activeSession: 1,
    },
    {
        id: 3,
        title: "Premium",
        type: "Premium",
        cost: 320000,
        image: imgDummy,
        rating: 4.8,
        capacity: 15,
        activeSession: 1,
    },
    {
        id: 4,
        title: "Executive",
        type: "Executive",
        cost: 400000,
        image: imgDummy,
        rating: 4.9,
        capacity: 12,
        activeSession: 1,
    },
    {
        id: 5,
        title: "Standard",
        type: "Standard",
        cost: 250000,
        image: imgDummy,
        rating: 4.5,
        capacity: 8,
        activeSession: 1,
    },
    {
        id: 6,
        title: "Meeting Room A",
        type: "Meeting",
        cost: 300000,
        image: imgDummy,
        rating: 4.6,
        capacity: 10,
        activeSession: 1,
    },
    {
        id: 7,
        title: "Meeting Room B",
        type: "Meeting",
        cost: 300000,
        image: imgDummy,
        rating: 4.7,
        capacity: 9,
        activeSession: 1,
    },
    {
        id: 8,
        title: "Bohe Room",
        type: "Bohe",
        cost: 350000,
        image: imgDummy,
        rating: 4.9,
        capacity: 15,
        activeSession: 1,
    },
    {
        id: 9,
        title: "Conference Hall",
        type: "Conference",
        cost: 500000,
        image: imgDummy,
        rating: 5.0,
        capacity: 25,
        activeSession: 1,
    }
];

export default dummy;
